// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhncrzrftprkarqttxoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVobmNyenJmdHBya2FycXR0eG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjAzMTYsImV4cCI6MjA2OTUzNjMxNn0.Mk4Fj9RhdmP0p6SByRueCpN1SPz7Fj7i41EUOJJkFog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});